In [99]:
import numpy as np
import math, random
import os, sys
import warnings
warnings.filterwarnings('ignore')
random.seed(42)

In [2]:
matrix = np.array([[7.14, 1.28, 0.79, 1.12],
                  [1.28, 3.28, 1.3, 0.16],
                  [0.79, 1.3, 6.32, 2.1],
                  [1.12, 0.16, 2.1, 5.22]])
print(matrix)

[[7.14 1.28 0.79 1.12]
 [1.28 3.28 1.3  0.16]
 [0.79 1.3  6.32 2.1 ]
 [1.12 0.16 2.1  5.22]]


In [3]:
def find_index(matrix):
    max_ = np.fabs(matrix[0][1])
    k, t = 0, 1
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            if ((i !=j and i < j) and np.fabs(matrix[i][j]) > max_):
                max_ = np.fabs(matrix[i][j])
                k, t = i, j
    return k, t

In [4]:
find_t = lambda x: 1/(x - np.sqrt(pow(x,2) + 1)) if x < 0 else 1/(x + np.sqrt(pow(x,2) + 1))

In [5]:
def make_T(I, c, s, i, j):
    I[i][i], I[j][j] = c, c
    if (j > i):
        I[i][j] = s
        I[j][i] = -s
    else:
        I[i][j] = -s
        I[j][i] = s
    return I

In [6]:
def W_2(matrix):
    return pow(np.linalg.norm(matrix, 'fro'), 2) - \
sum([pow(matrix[i][j], 2) for i in range(matrix.shape[0]) for j in range(matrix.shape[1]) if i == j])
W_2(matrix)

19.284999999999997

In [7]:
def jakobi(matrix, eps):
    A = matrix
    iter_ = 0
    Q = np.eye(matrix.shape[0])
    
    while((W_2(A)) > eps):
        
        print("Current matrix: \n{}".format(A))
        
        i, j = find_index(A)
        
        print('i, j: {}, {}'.format(i, j))
        
        alpha, beta, gamma = A[i][i], A[j][j], A[i][j]
        print('alpha, beta, gamma: {}, {}, {}'.format(alpha, beta, gamma))
        
        ksi = - (alpha - beta) / (2*gamma)
    
        c = 1/np.sqrt(1+pow(find_t(ksi), 2))
        s = c*find_t(ksi)
        delta = sum([pow(A[i][j], 2) for i in range(A.shape[0]) for j in range(A.shape[1]) if i == j])
        
        print('ksi, t, c, s: {}, {}, {}, {}'.format(ksi, find_t(ksi), c, s))
        
        T = make_T(np.eye(A.shape[0]), c, s, i, j)
        Q = np.dot(Q, T)
        print(Q,'\n')
        print(T)
        
        print(pow(c,2) + pow(s, 2) == 1)
        print('delta, 2w, frobenius_norm, {}, {}, {}'.format(delta, W_2(A), pow(np.linalg.norm(A, 'fro'), 2)))
        
        iter_+=1
        
        A = np.dot(np.dot(T.T, A), T)
        print('New_matrix: \n{}'.format(A))
    
    print('nb_iterations: {}'.format(iter_))
    return A, Q

In [8]:
m = jakobi(matrix, 1e-5)

Current matrix: 
[[7.14 1.28 0.79 1.12]
 [1.28 3.28 1.3  0.16]
 [0.79 1.3  6.32 2.1 ]
 [1.12 0.16 2.1  5.22]]
i, j: 2, 3
alpha, beta, gamma: 6.32, 5.22, 2.1
ksi, t, c, s: -0.26190476190476203, -0.771823492671067, 0.7916310352170648, -0.6109994305080474
[[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [ 0.          0.          0.79163104 -0.61099943]
 [ 0.          0.          0.61099943  0.79163104]] 

[[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [ 0.          0.          0.79163104 -0.61099943]
 [ 0.          0.          0.61099943  0.79163104]]
False
delta, 2w, frobenius_norm, 128.9288, 19.284999999999997, 148.2138
New_matrix: 
[[ 7.14000000e+00  1.28000000e+00  1.30970788e+00  4.03937209e-01]
 [ 1.28000000e+00  3.28000000e+00  1.12688025e+00 -6.67638294e-01]
 [ 1.30970788e+00  1.12688025e+00  7.94082933e+00 -4.44089210e-16]
 [ 4.03937209e-01 -6.67638294e-01  2.22044605e-16

In [9]:
def get_diag_el(matrix):
    return np.array([matrix[i][j] for i in range(matrix.shape[0]) for j in range(matrix.shape[1]) if i == j])

In [10]:
get_diag_el(m[0])

array([6.22854436, 2.34823566, 9.37018515, 4.01303483])

In [11]:
np.linalg.eigvals(matrix)

array([9.37018515, 6.22854551, 2.34823534, 4.01303399])

In [12]:
np.linalg.eig(matrix)

(array([9.37018515, 6.22854551, 2.34823534, 4.01303399]),
 array([[ 0.59806645,  0.76608415, -0.23179621,  0.04125671],
        [ 0.26443607,  0.06865117,  0.81951329, -0.50374454],
        [ 0.59196826, -0.56089555, -0.4007216 , -0.41760263],
        [ 0.4711302 , -0.30626504,  0.33777314,  0.75508103]]))

In [13]:
m

(array([[ 6.22854436e+00, -1.10983564e-03, -1.35579952e-05,
         -1.35748780e-03],
        [-1.10983564e-03,  2.34823566e+00, -2.21204160e-07,
          6.53525518e-19],
        [-1.35579952e-05, -2.21204160e-07,  9.37018515e+00,
         -2.93953823e-05],
        [-1.35748780e-03,  1.81131557e-16, -2.93953823e-05,
          4.01303483e+00]]),
 array([[ 0.76604038, -0.23201534,  0.59806997,  0.04078397],
        [ 0.06857575,  0.81949381,  0.26443363, -0.50378776],
        [-0.56126846, -0.400561  ,  0.59196354, -0.41726222],
        [-0.30570774,  0.3378604 ,  0.47113303,  0.75526604]]))

In [14]:
m[1]

array([[ 0.76604038, -0.23201534,  0.59806997,  0.04078397],
       [ 0.06857575,  0.81949381,  0.26443363, -0.50378776],
       [-0.56126846, -0.400561  ,  0.59196354, -0.41726222],
       [-0.30570774,  0.3378604 ,  0.47113303,  0.75526604]])

In [15]:
eigenvals = get_diag_el(m[0])

In [16]:
eigenvals

array([6.22854436, 2.34823566, 9.37018515, 4.01303483])

In [17]:
eigenvectors = [m[1][:, i] for i in range(4)]
eigenvectors

[array([ 0.76604038,  0.06857575, -0.56126846, -0.30570774]),
 array([-0.23201534,  0.81949381, -0.400561  ,  0.3378604 ]),
 array([0.59806997, 0.26443363, 0.59196354, 0.47113303]),
 array([ 0.04078397, -0.50378776, -0.41726222,  0.75526604])]

In [18]:
for l, v in zip(eigenvals, eigenvectors):
    print(np.dot(matrix, v) - np.dot(l, v))

[ 0.00019403 -0.0002292   0.00100296 -0.00140662]
[-8.50311203e-04 -7.61663050e-05  6.22784799e-04  3.39181124e-04]
[-1.15335094e-05  1.36980088e-05  1.99638635e-05 -1.81312861e-05]
[-0.00105747 -0.00010086  0.00074451  0.00040115]


In [19]:
Matrix = np.array([[7.14, 1.16, 0.91, 1.12],
                  [1.16, 3.28, 1.3, 0.16],
                  [0.91, 1.3, 6.32, 2.1],
                  [1.12, 0.16, 2.1, 5.22]])
u = jakobi(Matrix, 1e-5)

Current matrix: 
[[7.14 1.16 0.91 1.12]
 [1.16 3.28 1.3  0.16]
 [0.91 1.3  6.32 2.1 ]
 [1.12 0.16 2.1  5.22]]
i, j: 2, 3
alpha, beta, gamma: 6.32, 5.22, 2.1
ksi, t, c, s: -0.26190476190476203, -0.771823492671067, 0.7916310352170648, -0.6109994305080474
[[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [ 0.          0.          0.79163104 -0.61099943]
 [ 0.          0.          0.61099943  0.79163104]] 

[[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [ 0.          0.          0.79163104 -0.61099943]
 [ 0.          0.          0.61099943  0.79163104]]
False
delta, 2w, frobenius_norm, 128.9288, 19.107400000000013, 148.0362
New_matrix: 
[[ 7.14000000e+00  1.16000000e+00  1.40470360e+00  3.30617278e-01]
 [ 1.16000000e+00  3.28000000e+00  1.12688025e+00 -6.67638294e-01]
 [ 1.40470360e+00  1.12688025e+00  7.94082933e+00 -4.44089210e-16]
 [ 3.30617278e-01 -6.67638294e-01  2.22044605e-16

In [73]:
u

(array([[ 6.11518352e+00, -5.96569323e-04, -1.72575582e-06,
         -3.43469953e-04],
        [-5.96569323e-04,  2.41230954e+00, -4.33680869e-19,
          3.90416647e-08],
        [-1.72575582e-06, -2.79290480e-16,  9.41860160e+00,
         -4.03006581e-05],
        [-3.43469953e-04,  3.90416645e-08, -4.03006581e-05,
          4.01390534e+00]]),
 array([[ 0.77412594, -0.20370023,  0.59806362,  0.0394355 ],
        [ 0.04742168,  0.82198759,  0.25211345, -0.50845491],
        [-0.54929579, -0.4087707 ,  0.59913803, -0.41498708],
        [-0.31105362,  0.34021924,  0.46882016,  0.75346146]]))

In [74]:
get_diag_el(u[0])

array([6.11518352, 2.41230954, 9.4186016 , 4.01390534])

In [75]:
u[1]

array([[ 0.77412594, -0.20370023,  0.59806362,  0.0394355 ],
       [ 0.04742168,  0.82198759,  0.25211345, -0.50845491],
       [-0.54929579, -0.4087707 ,  0.59913803, -0.41498708],
       [-0.31105362,  0.34021924,  0.46882016,  0.75346146]])

In [76]:
for l, v in zip(get_diag_el(u[0]), [u[1][:, i] for i in range(4)]):
    print(np.dot(matrix, v) - np.dot(l, v))

[ 0.07171304  0.09257894 -0.09250975 -0.00046256]
[ 0.14722918 -0.02447234  0.0247717   0.00018559]
[-4.16458740e-02  7.17880432e-02 -7.17499617e-02 -2.98281901e-05]
[-1.15061393e-02  4.70584360e-03 -4.56775479e-03  8.79570925e-05]


In [131]:
def Degree_method(matrix, eps):
    max_iter = 100
    X = [i for i in range(max_iter)]
    X[0] = np.array([i for i in range(matrix.shape[0])]).T
    X[1] = np.dot(matrix, X[0])
    i = random.choice([i for i in range(len(X[1]))])
    lambda_1 = (X[1][i]) / (X[0][i])
    lambda_0 = 1
    k = 1
    while(np.fabs(lambda_1 - lambda_0) > eps):
        X[k] = np.dot(matrix, X[k-1])
        X[k+1] = np.dot(matrix, X[k])
        i = random.choice([i for i in range(len(X[k]))])
        lambda_0 = (X[k][i]) / (X[k-1][i])
        lambda_1 = X[k+1][i] / X[k][i]
        
        k+=1
    return lambda_1, X[k] / np.linalg.norm(X[k])

In [132]:
Degree_method(matrix, 1e-5)

(9.37019890164683, array([0.59805787, 0.2644353 , 0.59197455, 0.47113363]))

In [134]:
Degree_method(matrix - np.dot(Degree_method(matrix, 1e-5)[0], np.eye(4)), 1e-5)[0] + 9.370194290580299

2.3482038621359926

In [136]:
Degree_method(matrix - np.dot(Degree_method(matrix, 1e-5)[0], np.eye(4)), 1e-5)[1]

array([-0.23179547,  0.81950428, -0.40072906,  0.33778664])

In [130]:
np.linalg.eig(matrix)

(array([9.37018515, 6.22854551, 2.34823534, 4.01303399]),
 array([[ 0.59806645,  0.76608415, -0.23179621,  0.04125671],
        [ 0.26443607,  0.06865117,  0.81951329, -0.50374454],
        [ 0.59196826, -0.56089555, -0.4007216 , -0.41760263],
        [ 0.4711302 , -0.30626504,  0.33777314,  0.75508103]]))